apiVersion: v1
kind: Secret
metadata:
  name: postgres-keycloak-secret
  namespace: wiki
type: Opaque
stringData:
  POSTGRES_PASSWORD: keycloak_password
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-app-secret
  namespace: wiki
type: Opaque
stringData:
  POSTGRES_PASSWORD: wiki_password
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: wiki
type: Opaque
stringData:
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
  KC_DB_PASSWORD: keycloak_password
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: wiki
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: wiki_admin
  MONGO_INITDB_ROOT_PASSWORD: mongo_password
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: wiki
type: Opaque
stringData:
  RABBITMQ_DEFAULT_PASS: rabbitmq_password
  RABBITMQ_ERLANG_COOKIE: secret_cookie_value
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: wiki
type: Opaque
stringData:
  REDIS_PASSWORD: redis_password
